config/routes.rb
Rails.application.routes.draw do
  get 'select_profile' => 'select_profile#index'

  get 'select_profile/activate/:id' => 'select_profile#activate'

  get 'play' => 'play#index'
  post 'play' => 'play#index'

  post 'reset' => 'play#reset'
  get 'reset' => 'play#reset'

  get 'play/update'

  resources :handlers

  resources :hooks

  resources :extra_choices

  resources :mods

  resources :incarnations

  resources :profiles

  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/incarnation.rb
class Incarnation < ActiveRecord::Base
  belongs_to :profile
  belongs_to :location

  def self.create_for(profile)
    i = Incarnation.new
    i.profile = profile
    i.max_hitpoints = 100
    i.hitpoints = 100
    i.turns = 25
    i.experience = 0
    i.gold = 0
    i.title = "Firstyear"
    i.name = profile.name
    i.save
    i 

  end
end
=begin
   t.integer  "profile_id"
    t.string   "kind"
    t.string   "title"
    t.string   "name"
    t.string   "gender"
    t.string   "other_gender"
    t.integer  "gold"
    t.integer  "gems"
    t.integer  "hitpoints"
    t.integer  "max_hitpoints"
    t.integer  "mana"
    t.integer  "max_mana"
    t.integer  "experience"
    t.integer  "level"
    t.integer  "turns"
    t.integer  "location_id"
    t.binary   "coroutine"
    t.text     "display
=end

app/controllers/incarnations_controller.rb
class IncarnationsController < ApplicationController
  before_action :set_incarnation, only: [:show, :edit, :update, :destroy]

  # GET /incarnations
  # GET /incarnations.json
  def index
    @incarnations = Incarnation.all
  end

  # GET /incarnations/1
  # GET /incarnations/1.json
  def show
  end

  # GET /incarnations/new
  def new
    @incarnation = Incarnation.new
  end

  # GET /incarnations/1/edit
  def edit
  end

  # POST /incarnations
  # POST /incarnations.json
  def create
    @incarnation = Incarnation.new(incarnation_params)

    respond_to do |format|
      if @incarnation.save
        format.html { redirect_to @incarnation, notice: 'Incarnation was successfully created.' }
        format.json { render :show, status: :created, location: @incarnation }
      else
        format.html { render :new }
        format.json { render json: @incarnation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incarnations/1
  # PATCH/PUT /incarnations/1.json
  def update
    respond_to do |format|
      if @incarnation.update(incarnation_params)
        format.html { redirect_to @incarnation, notice: 'Incarnation was successfully updated.' }
        format.json { render :show, status: :ok, location: @incarnation }
      else
        format.html { render :edit }
        format.json { render json: @incarnation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incarnations/1
  # DELETE /incarnations/1.json
  def destroy
    @incarnation.destroy
    respond_to do |format|
      format.html { redirect_to incarnations_url, notice: 'Incarnation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incarnation
      @incarnation = Incarnation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incarnation_params
      params.require(:incarnation).permit(:profile_id, :kind, :title, :name, :gender, :other_gender, :gold, :gems, :hitpoints, :max_hitpoints, :mana, :max_mana, :experience, :level, :turns, :location_id, :coroutine, :display)
    end
end

app/helpers/incarnations_helper.rb
module IncarnationsHelper
end

app/views/incarnations/_form.html.slim
= simple_form_for(@incarnation) do |f|
  = f.error_notification

  .form-inputs
    = f.association :profile
    = f.input :kind
    = f.input :title
    = f.input :name
    = f.input :gender
    = f.input :other_gender
    = f.input :gold
    = f.input :gems
    = f.input :hitpoints
    = f.input :max_hitpoints
    = f.input :mana
    = f.input :max_mana
    = f.input :experience
    = f.input :level
    = f.input :turns
    = f.association :location


  .form-actions
    = f.button :submit

app/views/incarnations/edit.html.slim
h1 Editing incarnation

== render 'form'

= link_to 'Show', @incarnation
'|
= link_to 'Back', incarnations_path

app/views/incarnations/index.html.slim
h1 Listing incarnations

table
  thead
    tr
      th Profile
      th Kind
      th Title
      th Name
      th Gender
      th Other gender
      th Gold
      th Gems
      th Hitpoints
      th Max hitpoints
      th Mana
      th Max mana
      th Experience
      th Level
      th Turns
      th Location
      th Coroutine
      th Display
      th
      th
      th

  tbody
    - @incarnations.each do |incarnation|
      tr
        td = incarnation.profile
        td = incarnation.kind
        td = incarnation.title
        td = incarnation.name
        td = incarnation.gender
        td = incarnation.other_gender
        td = incarnation.gold
        td = incarnation.gems
        td = incarnation.hitpoints
        td = incarnation.max_hitpoints
        td = incarnation.mana
        td = incarnation.max_mana
        td = incarnation.experience
        td = incarnation.level
        td = incarnation.turns
        td = incarnation.location
        td = incarnation.coroutine
        td = incarnation.display
        td = link_to 'Show', incarnation
        td = link_to 'Edit', edit_incarnation_path(incarnation)
        td = link_to 'Destroy', incarnation, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Incarnation', new_incarnation_path

app/views/incarnations/new.html.slim
h1 New incarnation

== render 'form'

= link_to 'Back', incarnations_path

app/views/incarnations/show.html.slim
p#notice = notice

p
  strong Profile:
  = @incarnation.profile
p
  strong Kind:
  = @incarnation.kind
p
  strong Title:
  = @incarnation.title
p
  strong Name:
  = @incarnation.name
p
  strong Gender:
  = @incarnation.gender
p
  strong Other gender:
  = @incarnation.other_gender
p
  strong Gold:
  = @incarnation.gold
p
  strong Gems:
  = @incarnation.gems
p
  strong Hitpoints:
  = @incarnation.hitpoints
p
  strong Max hitpoints:
  = @incarnation.max_hitpoints
p
  strong Mana:
  = @incarnation.mana
p
  strong Max mana:
  = @incarnation.max_mana
p
  strong Experience:
  = @incarnation.experience
p
  strong Level:
  = @incarnation.level
p
  strong Turns:
  = @incarnation.turns
p
  strong Location:
  = @incarnation.location
p
  strong Coroutine:
  = @incarnation.coroutine
p
  strong Display:
  = @incarnation.display

= link_to 'Edit', edit_incarnation_path(@incarnation)
'|
= link_to 'Back', incarnations_path