config/routes.rb
Rails.application.routes.draw do
  get 'select_profile' => 'select_profile#index'

  get 'select_profile/activate/:id' => 'select_profile#activate'

  get 'play' => 'play#index'
  post 'play' => 'play#index'

  post 'reset' => 'play#reset'
  get 'reset' => 'play#reset'

  get 'play/update'

  resources :handlers

  resources :hooks

  resources :extra_choices

  resources :mods

  resources :incarnations

  resources :profiles

  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/handler.rb
class Handler < ActiveRecord::Base
  belongs_to :mod
  belongs_to :hook
end

app/controllers/handlers_controller.rb
class HandlersController < ApplicationController
  before_action :set_handler, only: [:show, :edit, :update, :destroy]

  # GET /handlers
  # GET /handlers.json
  def index
    @handlers = Handler.all
  end

  # GET /handlers/1
  # GET /handlers/1.json
  def show
  end

  # GET /handlers/new
  def new
    @handler = Handler.new
  end

  # GET /handlers/1/edit
  def edit
  end

  # POST /handlers
  # POST /handlers.json
  def create
    @handler = Handler.new(handler_params)

    respond_to do |format|
      if @handler.save
        format.html { redirect_to @handler, notice: 'Handler was successfully created.' }
        format.json { render :show, status: :created, location: @handler }
      else
        format.html { render :new }
        format.json { render json: @handler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /handlers/1
  # PATCH/PUT /handlers/1.json
  def update
    respond_to do |format|
      if @handler.update(handler_params)
        format.html { redirect_to @handler, notice: 'Handler was successfully updated.' }
        format.json { render :show, status: :ok, location: @handler }
      else
        format.html { render :edit }
        format.json { render json: @handler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /handlers/1
  # DELETE /handlers/1.json
  def destroy
    @handler.destroy
    respond_to do |format|
      format.html { redirect_to handlers_url, notice: 'Handler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_handler
      @handler = Handler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def handler_params
      params.require(:handler).permit(:mod_id, :hook_id, :code, :priority)
    end
end

app/helpers/handlers_helper.rb
module HandlersHelper
end

app/views/handlers/_form.html.slim
= simple_form_for(@handler) do |f|
  = f.error_notification

  .form-inputs
    = f.association :mod
    = f.association :hook
    = f.input :code
    = f.input :priority

  .form-actions
    = f.button :submit

app/views/handlers/edit.html.slim
h1 Editing handler

== render 'form'

= link_to 'Show', @handler
'|
= link_to 'Back', handlers_path

app/views/handlers/index.html.slim
h1 Listing handlers

table
  thead
    tr
      th Mod
      th Hook
      th Code
      th Priority
      th
      th
      th

  tbody
    - @handlers.each do |handler|
      tr
        td = handler.mod
        td = handler.hook
        td = handler.code
        td = handler.priority
        td = link_to 'Show', handler
        td = link_to 'Edit', edit_handler_path(handler)
        td = link_to 'Destroy', handler, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Handler', new_handler_path

app/views/handlers/new.html.slim
h1 New handler

== render 'form'

= link_to 'Back', handlers_path

app/views/handlers/show.html.slim
p#notice = notice

p
  strong Mod:
  = @handler.mod
p
  strong Hook:
  = @handler.hook
p
  strong Code:
  = @handler.code
p
  strong Priority:
  = @handler.priority

= link_to 'Edit', edit_handler_path(@handler)
'|
= link_to 'Back', handlers_path