config/routes.rb
Rails.application.routes.draw do
  get 'select_profile' => 'select_profile#index'

  get 'select_profile/activate/:id' => 'select_profile#activate'

  get 'play' => 'play#index'
  post 'play' => 'play#index'

  post 'reset' => 'play#reset'
  get 'reset' => 'play#reset'

  get 'play/update'

  resources :handlers

  resources :hooks

  resources :extra_choices

  resources :mods

  resources :incarnations

  resources :profiles

  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/extra_choice.rb
class ExtraChoice < ActiveRecord::Base
  belongs_to :mod
  belongs_to :choice_location, class_name: "Location"
  belongs_to :destination, class_name: "Location"
end

app/controllers/extra_choices_controller.rb
class ExtraChoicesController < ApplicationController
  before_action :set_extra_choice, only: [:show, :edit, :update, :destroy]

  # GET /extra_choices
  # GET /extra_choices.json
  def index
    @extra_choices = ExtraChoice.all
  end

  # GET /extra_choices/1
  # GET /extra_choices/1.json
  def show
  end

  # GET /extra_choices/new
  def new
    @extra_choice = ExtraChoice.new
  end

  # GET /extra_choices/1/edit
  def edit
  end

  # POST /extra_choices
  # POST /extra_choices.json
  def create
    @extra_choice = ExtraChoice.new(extra_choice_params)

    respond_to do |format|
      if @extra_choice.save
        format.html { redirect_to @extra_choice, notice: 'Extra choice was successfully created.' }
        format.json { render :show, status: :created, location: @extra_choice }
      else
        format.html { render :new }
        format.json { render json: @extra_choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /extra_choices/1
  # PATCH/PUT /extra_choices/1.json
  def update
    respond_to do |format|
      if @extra_choice.update(extra_choice_params)
        format.html { redirect_to @extra_choice, notice: 'Extra choice was successfully updated.' }
        format.json { render :show, status: :ok, location: @extra_choice }
      else
        format.html { render :edit }
        format.json { render json: @extra_choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /extra_choices/1
  # DELETE /extra_choices/1.json
  def destroy
    @extra_choice.destroy
    respond_to do |format|
      format.html { redirect_to extra_choices_url, notice: 'Extra choice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_extra_choice
      @extra_choice = ExtraChoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def extra_choice_params
      params.require(:extra_choice).permit(:mod_id, :title, :choice_location_id, :destination_id, :priority)
    end
end

app/helpers/extra_choices_helper.rb
module ExtraChoicesHelper
end

app/views/extra_choices/_form.html.slim
= simple_form_for(@extra_choice) do |f|
  = f.error_notification

  .form-inputs
    = f.association :mod
    = f.input :title
    = f.association :choice_location
    = f.association :destination
    = f.input :priority

  .form-actions
    = f.button :submit

app/views/extra_choices/edit.html.slim
h1 Editing extra_choice

== render 'form'

= link_to 'Show', @extra_choice
'|
= link_to 'Back', extra_choices_path

app/views/extra_choices/index.html.slim
h1 Listing extra_choices

table
  thead
    tr
      th Mod
      th Title
      th Choice location
      th Destination
      th Priority
      th
      th
      th

  tbody
    - @extra_choices.each do |extra_choice|
      tr
        td = extra_choice.mod
        td = extra_choice.title
        td = extra_choice.choice_location
        td = extra_choice.destination
        td = extra_choice.priority
        td = link_to 'Show', extra_choice
        td = link_to 'Edit', edit_extra_choice_path(extra_choice)
        td = link_to 'Destroy', extra_choice, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Extra choice', new_extra_choice_path

app/views/extra_choices/new.html.slim
h1 New extra_choice

== render 'form'

= link_to 'Back', extra_choices_path

app/views/extra_choices/show.html.slim
p#notice = notice

p
  strong Mod:
  = @extra_choice.mod
p
  strong Title:
  = @extra_choice.title
p
  strong Choice location:
  = @extra_choice.choice_location
p
  strong Destination:
  = @extra_choice.destination
p
  strong Priority:
  = @extra_choice.priority

= link_to 'Edit', edit_extra_choice_path(@extra_choice)
'|
= link_to 'Back', extra_choices_path