config/routes.rb
Rails.application.routes.draw do
  get 'select_profile' => 'select_profile#index'

  get 'select_profile/activate/:id' => 'select_profile#activate'

  get 'play' => 'play#index'
  post 'play' => 'play#index'

  post 'reset' => 'play#reset'
  get 'reset' => 'play#reset'

  get 'play/update'

  resources :handlers

  resources :hooks

  resources :extra_choices

  resources :mods

  resources :incarnations

  resources :profiles

  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/hook.rb
class Hook < ActiveRecord::Base
  belongs_to :mod
  belongs_to :location
end

app/controllers/hooks_controller.rb
class HooksController < ApplicationController
  before_action :set_hook, only: [:show, :edit, :update, :destroy]

  # GET /hooks
  # GET /hooks.json
  def index
    @hooks = Hook.all
  end

  # GET /hooks/1
  # GET /hooks/1.json
  def show
  end

  # GET /hooks/new
  def new
    @hook = Hook.new
  end

  # GET /hooks/1/edit
  def edit
  end

  # POST /hooks
  # POST /hooks.json
  def create
    @hook = Hook.new(hook_params)

    respond_to do |format|
      if @hook.save
        format.html { redirect_to @hook, notice: 'Hook was successfully created.' }
        format.json { render :show, status: :created, location: @hook }
      else
        format.html { render :new }
        format.json { render json: @hook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hooks/1
  # PATCH/PUT /hooks/1.json
  def update
    respond_to do |format|
      if @hook.update(hook_params)
        format.html { redirect_to @hook, notice: 'Hook was successfully updated.' }
        format.json { render :show, status: :ok, location: @hook }
      else
        format.html { render :edit }
        format.json { render json: @hook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hooks/1
  # DELETE /hooks/1.json
  def destroy
    @hook.destroy
    respond_to do |format|
      format.html { redirect_to hooks_url, notice: 'Hook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hook
      @hook = Hook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hook_params
      params.require(:hook).permit(:mod_id, :location_id, :name, :kind)
    end
end

app/helpers/hooks_helper.rb
module HooksHelper
end

app/views/hooks/_form.html.slim
= simple_form_for(@hook) do |f|
  = f.error_notification

  .form-inputs
    = f.association :mod
    = f.association :location
    = f.input :name
    = f.input :kind

  .form-actions
    = f.button :submit

app/views/hooks/edit.html.slim
h1 Editing hook

== render 'form'

= link_to 'Show', @hook
'|
= link_to 'Back', hooks_path

app/views/hooks/index.html.slim
h1 Listing hooks

table
  thead
    tr
      th Mod
      th Location
      th Name
      th Kind
      th
      th
      th

  tbody
    - @hooks.each do |hook|
      tr
        td = hook.mod
        td = hook.location
        td = hook.name
        td = hook.kind
        td = link_to 'Show', hook
        td = link_to 'Edit', edit_hook_path(hook)
        td = link_to 'Destroy', hook, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Hook', new_hook_path

app/views/hooks/new.html.slim
h1 New hook

== render 'form'

= link_to 'Back', hooks_path

app/views/hooks/show.html.slim
p#notice = notice

p
  strong Mod:
  = @hook.mod
p
  strong Location:
  = @hook.location
p
  strong Name:
  = @hook.name
p
  strong Kind:
  = @hook.kind

= link_to 'Edit', edit_hook_path(@hook)
'|
= link_to 'Back', hooks_path